package java02;
class Java02 {
  void basic() {
    var n = 2;
    var i = 0;
    while (i < n) {
      System.out.println(0);
      i = i + 1;
    }
    System.out.println(i);
  }
  void q0() {
    var n = 5;
    var i = 0;
    while(i < n) {
      System.out.println(i);
      i = i+1;
    }
  }

  void q1() {
    var n = 5;
    var i = 0;
    while (i < n) {
      System.out.println(i+1);
      i = i+1;
    }
  }

  void q2() {
    var n = 5;
    var i = 0;
    while (i < n) {
      System.out.println(i*n);
      i = i + 1;
    }
  }

  void q3() {
    var n = 5;
    var i = 0;
    while (i < n) {
      System.out.println(i*n+1);
      i = i + 1;
    }
  }

  void q4() {
    var n = 5;
    var i = 0;
    while (i < n) {
      System.out.println((i+1)*n);
      i = i + 1;
    }
  }

  void q5() {
    var n = 5;
    var i = 0;
    while (i < n) {
      System.out.println(n-i);
      i = i + 1;
    }
  }

  void q6() {
    var n = 5;
    var i = 0;
    while (i < n) {
      System.out.println((n-i)*n);
      i = i + 1;
    }
  }

  void q7() {
    var n = 5;
    var i = 0;
    while (i < n) {
      System.out.println(n-i-1);
      i = i + 1;
    }
  }

  void q8() {
    var n = 5;
    var i = 0;
    while (i < n) {
      System.out.println((n-i-1)*n);
      i = i + 1;
    }
  }

  void q9() {
    var n = 5;
    var i = 0;
    while (i < n) {
      System.out.println(i*2);
      i = i + 1;
    }
  }

  void q10() {
    var n = 5;
    var i = 0;
    while (i < n) {
      System.out.println(i*2+1);
      i = i + 1;
    }
  }

  void q11() {
    var n = 5;
    var i = 0;
    while (i < n) {
      System.out.println((i+1)*2);
      i = i + 1;
    }
  }

  void q12() {
    var n = 5;
    var i = 0;
    while (i < n) {
      System.out.println((n-i)*2);
      i = i + 1;
    }
  }

  void q13() {
    var n = 5;
    var i = 0;
    while (i < n) {
      System.out.println((n-i-1)*2);
      i = i + 1;
    }
  }

  void q14() {
    var n = 5;
    var i = 0;
    while (i < n) {
      System.out.println(i%2);
      i = i + 1;
    }
  }

  void q15() {
    var n = 5;
    var i = 0;
    while (i < n) {
      System.out.println((i+1)%2);
      i = i + 1;
    }
  }

  void q16() {
    var n = 6;
    var i = 0;
    while (i < n) {
      System.out.println(i/2);
      i = i + 1;
    }
  }

  void q17() {
    var n = 6;
    var i = 0;
    while (i < n) {
      System.out.println(i/2%2);
      i = i + 1;
    }
  }

  void q18() {
    var n = 5;
    var i = 0;
    while (i < n) {
      System.out.println(i==2);
      i = i + 1;
    }
  }

  void q19() {
    var n = 5;
    var i = 0;
    while (i < n)
    {
      System.out.println(i!=2);
      i = i + 1;
    }
  }

  void q20() {
    var n = 5;
    var i = 0;
    while (i < n) {
      System.out.println(i<2);
      i = i + 1;
    }
  }

  void q21() {
    var n = 5;
    var i = 0;
    while (i < n) {
      System.out.println(i>2);
      i = i + 1;
    }
  }

  public static void main(String[] args) {
    var l = new java02.Java02();
    l.q21();
  }
}
