package java03;
class Java03 {
  void basic() {
    var n = 5;
    var i = 0;
    while (i < n) {
      var j = 0;
      while (j < n) {
        System.out.printf("%3d", 0);
        j = j + 1;
      }
      System.out.println();
      i = i + 1;
    }
  }

  void q0() {
    var n = 5;
    var i = 0;
    while (i < n) {
      var j = 0;
      while (j < n) {
        System.out.printf("%3d", i);
        j = j + 1;
      }
      System.out.println();
      i = i + 1;
    }
  }

  void q1() {
    var n = 5;
    var i = 0;
    while (i < n) {
      var j = 0;
      while (j < n) {
        System.out.printf("%3d", i+1);
        j = j + 1;
      }
      System.out.println();
      i = i + 1;
    }
  }

  void q2() {
    var n = 5;
    var i = 0;
    while (i < n) {
      var j = 0;
      while (j < n) {
        System.out.printf("%3d", n-i);
        j = j + 1;
      }
      System.out.println();
      i = i + 1;
    }
  }

  void q3() {
    var n = 5;
    var i = 0;
    while (i < n) {
      var j = 0;
      while (j < n) {
        System.out.printf("%3d", n-i-1);
        j = j + 1;
      }
      System.out.println();
      i = i + 1;
    }
  }

  void q4() {
    var n = 5;
    var i = 0;
    while (i < n) {
      var j = 0;
      while (j < n) {
        System.out.printf("%3d", j);
        j = j + 1;
      }
      System.out.println();
      i = i + 1;
    }
  }

  void q5() {
    var n = 5;
    var i = 0;
    while (i < n) {
      var j = 0;
      while (j < n) {
        System.out.printf("%3d", j+1);
        j = j + 1;
      }
      System.out.println();
      i = i + 1;
    }
  }

  void q6() {
    var n = 5;
    var i = 0;
    while (i < n) {
      var j = 0;
      while (j < n) {
        System.out.printf("%3d", n-j);
        j = j + 1;
      }
      System.out.println();
      i = i + 1;
    }
  }

  void q7() {
    var n = 5;
    var i = 0;
    while (i < n) {
      var j = 0;
      while (j < n) {
        System.out.printf("%3d", n-j-1);
        j = j + 1;
      }
      System.out.println();
      i = i + 1;
    }
  }

  void q8() {
    var n = 5;
    var i = 0;
    while (i < n) {
      var j = 0;
      while (j < n) {
        System.out.printf("%3d", i+j);
        j = j + 1;
      }
      System.out.println();
      i = i + 1;
    }
  }

  void q9() {
    var n = 5;
    var i = 0;
    while (i < n) {
      var j = 0;
      while (j < n) {
        System.out.printf("%3d", i+j+1);
        j = j + 1;
      }
      System.out.println();
      i = i + 1;
    }
  }

  void q10() {
    var n = 5;
    var i = 0;
    while (i < n) {
      var j = 0;
      while (j < n) {
        System.out.printf("%3d", (i+j)%2);
        j = j + 1;
      }
      System.out.println();
      i = i + 1;
    }
  }

  void q11() {
    var n = 5;
    var i = 0;
    while (i < n) {
      var j = 0;
      while (j < n) {
        System.out.printf("%3d", (i+j+1)%2);
        j = j + 1;
      }
      System.out.println();
      i = i + 1;
    }
  }

  void q12() {
    var n = 5;
    var i = 0;
    while (i < n) {
      var j = 0;
      while (j < n) {
        System.out.printf("%3d", i*n);
        j = j + 1;
      }
      System.out.println();
      i = i + 1;
    }
  }

  void q13() {
    var n = 5;
    var i = 0;
    while (i < n) {
      var j = 0;
      while (j < n) {
        System.out.printf("%3d", n*i+j);
        j = j + 1;
      }
      System.out.println();
      i = i + 1;
    }
  }

  void q14() {
    var n = 5;
    var i = 0;
    while (i < n) {
      var j = 0;
      while (j < n) {
        System.out.printf("%3d", n*i+1);
        j = j + 1;
      }
      System.out.println();
      i = i + 1;
    }
  }

  void q15() {
    var n = 5;
    var i = 0;
    while (i < n) {
      var j = 0;
      while (j < n) {
        System.out.printf("%3d", n*i+j+1);
        j = j + 1;
      }
      System.out.println();
      i = i + 1;
    }
  }

  void q16() {
    var n = 5;
    var i = 0;
    while (i < n) {
      var j = 0;
      while (j < n) {
        System.out.printf("%3d", (n-i)*n );
        j = j + 1;
      }
      System.out.println();
      i = i + 1;
    }
  }

  void q17() {
    var n = 5;
    var i = 0;
    while (i < n) {
      var j = 0;
      while (j < n) {
        System.out.printf("%3d", (n-i)*n-j);
        j = j + 1;
      }
      System.out.println();
      i = i + 1;
    }
  }

  void q18() {
    var n = 5;
    var i = 0;
    while (i < n) {
      var j = 0;
      while (j < n) {
        System.out.printf("%3d", (n-i-1)*n);
        j = j + 1;
      }
      System.out.println();
      i = i + 1;
    }
  }

  void q19() {
    var n = 5;
    var i = 0;
    while (i < n) {
      var j = 0;
      while (j < n) {
        System.out.printf("%3d", (n-i-1)*n+j);
        j = j + 1;
      }
      System.out.println();
      i = i + 1;
    }
  }

  void q20() {
    var n = 5;
    var i = 0;
    while (i < n) {
      var j = 0;
      while (j < n) {
        System.out.printf("%3d", (n-i-1)*n+j+1);
        j = j + 1;
      }
      System.out.println();
      i = i + 1;
    }
  }

  void q21() {
    var n = 5;
    var i = 0;
    while (i < n) {
      var j = 0;
      while (j < n) {
        System.out.printf("%3d", j*n);
        j = j + 1;
      }
      System.out.println();
      i = i + 1;
    }
  }

  void q22() {
    var n = 5;
    var i = 0;
    while (i < n) {
      var j = 0;
      while (j < n) {
        System.out.printf("%3d", j*n+i);
        j = j + 1;
      }
      System.out.println();
      i = i + 1;
    }
  }

  void q23() {
    var n = 5;
    var i = 0;
    while (i < n) {
      var j = 0;
      while (j < n) {
        System.out.printf("%3d", j*n+i+1);
        j = j + 1;
      }
      System.out.println();
      i = i + 1;
    }
  }

  void q24() {
    var n = 5;
    var i = 0;
    while (i < n) {
      var j = 0;
      while (j < n) {
        System.out.printf("%3d", (j+1)*n);
        j = j + 1;
      }
      System.out.println();
      i = i + 1;
    }
  }

  void q25() {
    var n = 5;
    var i = 0;
    while (i < n) {
      var j = 0;
      while (j < n) {
        System.out.printf("%3d", (j+1)*n-i);
        j = j+1;
      }
      System.out.println();
      i = i+1;
    }
  }

  void q26() {
    var n = 5;
    var i = 0;
    while(i < n) {
      var j = 0;
      while (j < n) {
          System.out.printf("%3d", (i+1)*n);
          j = j+1;
      }
      System.out.println();
      i = i+1;
    }
  }

  void q27() {
    var n = 5;
    var i = 0;
    while (i<n) {
      var j = 0;
      while(j < n) {
        System.out.printf("%3d", (i+1)*n-j);
        j = j+1;
      }
      System.out.println();
      i = i+1;
    }
  }

  void q28() {
    var n = 5;
    var i = 0;
    while (i < n) {
      var j = 0;
      while(j < n) {
        System.out.printf("%3d", j*2);
        j = j+1;
      }
      System.out.println();
      i = i+1;
    }
  }

  void q29() {
    var n = 5;
    var i = 0;
    while (i < n) {
      var j = 0;
      while (j < n) {
        System.out.printf("%3d", j*2+1);
        j = j+1;
      }
      System.out.println();
      i = i+1;
    } 
  }

  void q30() {
    var n = 5;
    var i = 0;
    while (i < n) {
      var j = 0;
      while (j < n) {
        System.out.printf("%3d", 2*n*i);
        j = j+1;
      }
      System.out.println();
      i = i+1;
    }
  }

  void q31() {
    var n = 5;
    var i = 0;
    while (i < n) {
      var j = 0;
      while (j < n) {
        System.out.printf("%3d", 2*n*i+2*j+1);
        j = j+1;
      }
      System.out.println();
      i = i+1;
    }
  }

  void q32() {
    var n = 5;
    var i = 0;
    while (i < n) {
      var j = 0;
      while (j < n-i) {
        System.out.printf("%3d", 0);
        j = j+1;
      }
      System.out.println();
      i = i+1;
    }
  }

  void q33() {
    var n = 5;
    var i = 0;
    while (i < n) {
      var j = 0;
      while (j < i+1) {
        System.out.printf("%3d", 1);
        j = j+1;
      }
      System.out.println();
      i = i+1;
    }
  }

  void q34() {
    var n = 5;
    var i = 0;
    while (i < n) {
      var j = 0;
      while (j < n-i) {
        System.out.printf("%3d", 0);
        j = j+1;
      }
      j = 0;
      while (j < i){
        System.out.printf("%3d", 1);
        j = j+1;
      }
      System.out.println();
      i = i+1;
    }
  }

  void q35() {
    var n = 5;
    var i = 0;
    while (i < n) {
      var j = 0;
      while (j < n-i-1) {
        System.out.printf("%3d", 0);
        j = j+1;
      }
      j = 0;
      while (j <i+1) {
        System.out.printf("%3d", 1);
        j = j+1;
      }
      System.out.println();
      i=i+1;
    }
  }

  void q36() {
    var n = 5;
    var i = 0;
    while (i < n) {
      var j = 0;
      while (j < i) {
        System.out.printf("%3d", 0);
        j = j+1;
      }
      j = 0;
      while (j < n-i) {
        System.out.printf("%3d", 1);
        j = j+1;
      }
      System.out.println();
      i = i+1;
    }
  }

  void q37() {
    var n = 5;
    var i = 0;
    while (i < n) {
      var j = 0;
      while (j < i+1) {
        System.out.printf("%3d", 0);
        j = j+1;
      }
      j = 0;
      while (j < n-i-1) {
        System.out.printf("%3d", 1);
        j = j+1;
      }
      System.out.println();
      i = i+1;
    }
  }

  public static void main(String[] args) {
    var l = new java03.Java03();
    l.q37();
  }
}
